// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductInfo.proto

package com.atom.grpc.api;

public final class ProductInfoProto {
  private ProductInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProductInfo.proto\"?\n\016ProductRequest\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003" +
      " \001(\t\"\032\n\tProductId\022\r\n\005value\030\001 \001(\t\"@\n\017Prod" +
      "uctResponse\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n" +
      "\013description\030\003 \001(\t2k\n\022ProductInfoService" +
      "\022)\n\naddProduct\022\017.ProductRequest\032\n.Produc" +
      "tId\022*\n\ngetProduct\022\n.ProductId\032\020.ProductR" +
      "esponseB\'\n\021com.atom.grpc.apiB\020ProductInf" +
      "oProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_ProductId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductId_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
